import type { PlayerCharacterAnimation, SpriteSheetConfig } from '@/core/types';

const ATLAS = 'playerCharacter' as const;

function atlas(
  partial: Omit<SpriteSheetConfig, 'imageKey'> & { imageKey?: string },
): SpriteSheetConfig {
  return { imageKey: ATLAS, ...partial };
}

/** All player animations from `character.gif`, plus legacy standalone fallbacks. */
export const PLAYER_CHARACTER_ANIMATIONS: readonly PlayerCharacterAnimation[] = [
  {
    id: 'armedStill',
    label: 'Armed still (6 facing)',
    standaloneKey: 'playerStill',
    config: atlas({
      countX: 1,
      countY: 6,
      width: 36,
      height: 70,
      clipX: 0,
      clipY: 70,
      offsetX: 0,
      offsetY: 50,
    }),
  },
  {
    id: 'unarmedStill',
    label: 'Unarmed still (8 facing)',
    standaloneKey: 'playerUnarmedStill',
    config: atlas({
      countX: 1,
      countY: 8,
      width: 36,
      height: 70,
      clipX: 0,
      clipY: 70,
      offsetX: 0,
      offsetY: 50,
    }),
  },
  {
    id: 'walking',
    label: 'Walking (8 frames, 6 facing)',
    standaloneKey: 'playerMoving',
    config: atlas({
      sourceX: 3010,
      sourceY: 8,
      totalFrames: 8,
      countX: 8,
      countY: 6,
      width: 44,
      height: 68,
      clipX: 44,
      clipY: 68,
      offsetX: 0,
      offsetY: 50,
    }),
  },
  {
    id: 'gunFire',
    label: 'Gun fire (5 frames, 6 facing)',
    standaloneKey: 'playerAttacking',
    config: atlas({
      countX: 5,
      countY: 6,
      width: 64,
      height: 79,
      clipX: 64,
      clipY: 79,
      offsetX: 10,
      offsetY: 58,
    }),
  },
  {
    id: 'scratchIdle',
    label: 'Scratch head idle',
    config: atlas({
      sourceX: 0,
      sourceY: 0,
      totalFrames: 12,
      countX: 12,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'runAway',
    label: 'Run away',
    config: atlas({
      sourceX: 696,
      sourceY: 0,
      totalFrames: 8,
      countX: 8,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'climb',
    label: 'Climb',
    config: atlas({
      sourceX: 1160,
      sourceY: 0,
      totalFrames: 8,
      countX: 8,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'kneel',
    label: 'Kneel / crouch',
    config: atlas({
      sourceX: 1624,
      sourceY: 0,
      totalFrames: 6,
      countX: 6,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'idleWindup',
    label: 'Idle wind-up',
    config: atlas({
      sourceX: 0,
      sourceY: 420,
      totalFrames: 8,
      countX: 8,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'kick',
    label: 'Kick',
    config: atlas({
      sourceX: 0,
      sourceY: 828,
      totalFrames: 6,
      countX: 6,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'hit',
    label: 'Hit react (single frame)',
    standaloneKey: 'playerHit',
    config: atlas({
      countX: 1,
      countY: 1,
      width: 68,
      height: 68,
      clipX: 0,
      clipY: 68,
      offsetX: 0,
      offsetY: 50,
    }),
  },
  {
    id: 'deathFall',
    label: 'Death fall (6 frames)',
    config: atlas({
      sourceX: 3010,
      sourceY: 418,
      totalFrames: 6,
      countX: 6,
      countY: 1,
      width: 58,
      height: 80,
      clipX: 58,
      clipY: 80,
      offsetX: 0,
      offsetY: 60,
    }),
  },
  {
    id: 'deathProne',
    label: 'Death prone',
    config: atlas({
      sourceX: 3010,
      sourceY: 498,
      countX: 1,
      countY: 1,
      width: 58,
      height: 34,
      clipX: 0,
      clipY: 34,
      offsetX: 0,
      offsetY: 20,
    }),
  },
] as const;

export function resolveAnimationConfig(
  animation: PlayerCharacterAnimation,
): SpriteSheetConfig {
  if (animation.standaloneKey) {
    return { ...animation.config, imageKey: animation.standaloneKey };
  }
  return animation.config;
}
