import type { SpriteSheetConfig } from '@/core/types';

export const PLAYER_SPRITES = {
  stillBasic: {
    imageKey: 'playerStill',
    countX: 8,
    countY: 6,
    width: 36,
    height: 70,
    clipX: 0,
    clipY: 70,
    offsetX: 0,
    offsetY: 50,
  },
  movingBasic: {
    imageKey: 'playerMoving',
    totalFrames: 8,
    countX: 8,
    countY: 6,
    width: 44,
    height: 68,
    clipX: 44,
    clipY: 68,
    offsetX: 0,
    offsetY: 50,
  },
  gunFireBasic: {
    imageKey: 'playerAttacking',
    totalFrames: 5,
    countX: 5,
    countY: 6,
    width: 64,
    height: 79,
    clipX: 64,
    clipY: 79,
    offsetX: 10,
    offsetY: 58,
  },
} as const satisfies Record<string, SpriteSheetConfig>;

export const ENEMY_SPRITES = {
  scorpionStill: {
    imageKey: 'scorpionStill',
    countX: 1,
    countY: 6,
    width: 59,
    height: 49,
    clipX: 59,
    clipY: 49,
    offsetX: 0,
    offsetY: 20,
  },
  scorpionMoving: {
    imageKey: 'scorpionMoving',
    totalFrames: 8,
    countX: 8,
    countY: 6,
    width: 59,
    height: 48,
    clipX: 59,
    clipY: 48,
    offsetX: 0,
    offsetY: 20,
  },
  scorpionAttack: {
    imageKey: 'scorpionAttacking',
    totalFrames: 11,
    countX: 11,
    countY: 6,
    width: 86,
    height: 68,
    clipX: 86,
    clipY: 68,
    offsetX: 10,
    offsetY: 40,
  },
  scorpionHit: {
    imageKey: 'scorpionHit',
    totalFrames: 6,
    countX: 6,
    countY: 6,
    width: 59,
    height: 48,
    clipX: 59,
    clipY: 48,
    offsetX: 0,
    offsetY: 20,
  },
  scorpionDeath: {
    imageKey: 'scorpionDeath',
    totalFrames: 5,
    countX: 5,
    countY: 6,
    width: 53.8,
    height: 34.83,
    clipX: 53.8,
    clipY: 34.83,
    offsetX: 0,
    offsetY: 10,
  },
  scorpionDead: {
    imageKey: 'scorpionDead',
    countX: 1,
    countY: 6,
    width: 53.8,
    height: 34.83,
    clipX: 0,
    clipY: 34.83,
    offsetX: 0,
    offsetY: 10,
  },
} as const satisfies Record<string, SpriteSheetConfig>;

export const UI_SPRITES = {
  bgDesert: '/assets/img/bg_desert.gif',
  bar: '/assets/img/bar.png',
  cursorStandard: '/assets/img/cursor_standard.png',
  cursorEnemy: '/assets/img/cursor_enemy.png',
  cursorRestricted: '/assets/img/cursor_restricted.png',
  cursorTouch: '/assets/img/cursor_touch.png',
} as const;

export const SPRITE_URLS: Record<string, string> = {
  playerCharacter: '/assets/sprites/character.gif',
  playerStill: '/assets/img/char_36_419.gif',
  playerUnarmedStill: '/assets/img/char_36_560.gif',
  playerMoving: '/assets/img/complete_movement.gif',
  playerAttacking: '/assets/img/char_gun_firing.png',
  playerHit: '/assets/img/char_68_68.png',
  scorpionStill: '/assets/img/enemy_scorpion_still.png',
  scorpionMoving: '/assets/img/enemy_scorpion_moving.png',
  scorpionAttacking: '/assets/img/enemy_scorpion_attack.png',
  scorpionHit: '/assets/img/enemy_scorpion_hit.png',
  scorpionDeath: '/assets/img/enemy_scorpion_death.png',
  scorpionDead: '/assets/img/enemy_scorpion_dead.png',
  ...UI_SPRITES,
};
